//+======================================================================
// $Source: /cvsroot/tango-cs/tango/jserver/snapshoting/SnapManager/SetEquipmentsWithSnapshotClass.java,v $
//
// Project:      Tango Device Server
//
// Description:  Java source code for the command TemplateClass of the
//               SnapManager class.
//
// $Author: chinkumo $
//
// $Revision: 1.3 $
//
// $Log: SetEquipmentsWithSnapshotClass.java,v $
// Revision 1.3  2005/11/29 17:34:34  chinkumo
// no message
//
// Revision 1.2.2.2  2005/11/29 16:18:25  chinkumo
// Code reformated (pogo compatible)
//
// Revision 1.2.2.1  2005/11/15 13:45:32  chinkumo
// ...
//
// Revision 1.2  2005/08/19 14:48:31  chinkumo
// no message
//
// Revision 1.1.2.1  2005/08/11 08:17:45  chinkumo
// The 'SetEquipement' command and thus functionnality was added.
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================



/**
 * @author	$Author: chinkumo $
 * @version	$Revision: 1.3 $
 */
package SnapManager;


import org.omg.CORBA.Any;

import fr.esrf.Tango.DevFailed;
import fr.esrf.Tango.DispLevel;
import fr.esrf.TangoDs.Command;
import fr.esrf.TangoDs.DeviceImpl;
import fr.esrf.TangoDs.TangoConst;
import fr.esrf.TangoDs.Util;

/**
 * Class Description:
 * This command is used to set values to equipments.
 */


public class SetEquipmentsWithSnapshotClass extends Command implements TangoConst
{
	//===============================================================
	/**
	 * Constructor for Command class SetEquipmentsWithSnapshotClass
	 *
	 * @param	name	command name
	 * @param	in	argin type
	 * @param	out	argout type
	 */
	//===============================================================
	public SetEquipmentsWithSnapshotClass(String name , int in , int out)
	{
		super(name , in , out);
	}

	//===============================================================
	/**
	 * Constructor for Command class SetEquipmentsWithSnapshotClass
	 *
	 * @param	name command name
	 * @param	in argin type
	 * @param	in_comments argin description
	 * @param	out argout type
	 * @param	out_comments argout description
	 */
	//===============================================================
	public SetEquipmentsWithSnapshotClass(String name , int in , int out , String in_comments , String out_comments)
	{
		super(name , in , out , in_comments , out_comments);
	}
	//===============================================================
	/**
	 * Constructor for Command class SetEquipmentsWithSnapshotClass
	 *
	 * @param	name command name
	 * @param	in argin type
	 * @param	in_comments argin description
	 * @param	out argout type
	 * @param	out_comments argout description
	 * @param	level The command display type OPERATOR or EXPERT
	 */
	//===============================================================
	public SetEquipmentsWithSnapshotClass(String name , int in , int out , String in_comments , String out_comments , DispLevel level)
	{
		super(name , in , out , in_comments , out_comments , level);
	}
	//===============================================================
	/**
	 * return the result of the device's command.
	 */
	//===============================================================
	public Any execute(DeviceImpl device , Any in_any) throws DevFailed
	{
		Util.out2.println("SetEquipmentsWithSnapshotClass.execute(): arrived");
		String[] argin = extract_DevVarStringArray(in_any);
		( ( SnapManager ) ( device ) ).set_equipments_with_snapshot(argin);
		return insert();
	}

	//===============================================================
	/**
	 * Check if it is allowed to execute the command.
	 */
	//===============================================================
	public boolean is_allowed(DeviceImpl device , Any data_in)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return true;
	}
}

//-----------------------------------------------------------------------------
/* end of $Source: /cvsroot/tango-cs/tango/jserver/snapshoting/SnapManager/SetEquipmentsWithSnapshotClass.java,v $ */
