//+======================================================================
// $Source: /cvsroot/tango-cs/tango/jserver/snapshoting/SnapArchiver/CreateNewContextCmd.java,v $
//
// Project:      Tango Device Server
//
// Description:  Java source code for the command TemplateClass of the
//               SnapArchiver class.
//
// $Author: chinkumo $
//
// $Revision: 1.5 $
//
// $Log: CreateNewContextCmd.java,v $
// Revision 1.5  2005/11/29 17:33:03  chinkumo
// no message
//
// Revision 1.4.10.2  2005/11/29 16:16:50  chinkumo
// Code reformated (pogo compatible)
//
// Revision 1.4.10.1  2005/11/15 13:46:17  chinkumo
// ...
//
// Revision 1.4  2005/06/15 14:02:53  chinkumo
// The device was regenerated in Tango V5.
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================



/**
 * @author	$Author: chinkumo $
 * @version	$Revision: 1.5 $
 */
package SnapArchiver;


import org.omg.CORBA.Any;

import fr.esrf.Tango.DevFailed;
import fr.esrf.Tango.DispLevel;
import fr.esrf.TangoDs.Command;
import fr.esrf.TangoDs.DeviceImpl;
import fr.esrf.TangoDs.TangoConst;
import fr.esrf.TangoDs.Util;

/**
 * Class Description:
 * This command is used to register a snapShot context.
 * All informations concerning the snapshot
 * (fr.soleil.snapArchivingApi.SnapshotingTools.Tools.SnapContext) are passed through an array (DEVVAR_STRINGARRAY).
 */


public class CreateNewContextCmd extends Command implements TangoConst
{
	//===============================================================
	/**
	 * Constructor for Command class CreateNewContextCmd
	 *
	 * @param	name	command name
	 * @param	in	argin type
	 * @param	out	argout type
	 */
	//===============================================================
	public CreateNewContextCmd(String name , int in , int out)
	{
		super(name , in , out);
	}

	//===============================================================
	/**
	 * Constructor for Command class CreateNewContextCmd
	 *
	 * @param	name command name
	 * @param	in argin type
	 * @param	in_comments argin description
	 * @param	out argout type
	 * @param	out_comments argout description
	 */
	//===============================================================
	public CreateNewContextCmd(String name , int in , int out , String in_comments , String out_comments)
	{
		super(name , in , out , in_comments , out_comments);
	}
	//===============================================================
	/**
	 * Constructor for Command class CreateNewContextCmd
	 *
	 * @param	name command name
	 * @param	in argin type
	 * @param	in_comments argin description
	 * @param	out argout type
	 * @param	out_comments argout description
	 * @param	level The command display type OPERATOR or EXPERT
	 */
	//===============================================================
	public CreateNewContextCmd(String name , int in , int out , String in_comments , String out_comments , DispLevel level)
	{
		super(name , in , out , in_comments , out_comments , level);
	}
	//===============================================================
	/**
	 * return the result of the device's command.
	 */
	//===============================================================
	public Any execute(DeviceImpl device , Any in_any) throws DevFailed
	{
		Util.out2.println("CreateNewContextCmd.execute(): arrived");
		String[] argin = extract_DevVarStringArray(in_any);
		( ( SnapArchiver ) ( device ) ).create_new_context(argin);
		return insert();
	}

	//===============================================================
	/**
	 * Check if it is allowed to execute the command.
	 */
	//===============================================================
	public boolean is_allowed(DeviceImpl device , Any data_in)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return true;
	}
}

//-----------------------------------------------------------------------------
/* end of $Source: /cvsroot/tango-cs/tango/jserver/snapshoting/SnapArchiver/CreateNewContextCmd.java,v $ */
