# Project version
set(LIBHDBPP_CASSANDRA_VERSION_MAJOR "0")
set(LIBHDBPP_CASSANDRA_VERSION_MINOR "10")
set(LIBHDBPP_CASSANDRA_VERSION_REVISION "0")
string(TIMESTAMP LIBHDBPP_CASSANDRA_TIMESTAMP "%Y-%m-%d %H:%M:%S")

# Version the shared library
set(LIBRARY_VERSION_MAJOR 7)
set(LIBRARY_VERSION_MINOR 0)
set(LIBRARY_VERSION_PATCH 1)

# Create the soname string
set(LIBRARY_VERSION_STRING ${LIBRARY_VERSION_MAJOR}.${LIBRARY_VERSION_MINOR}.${LIBRARY_VERSION_PATCH})