//+======================================================================
// $Source: /cvsroot/tango-cs/tango/jserver/snapshoting/SnapArchiver/SnapArchiverClass.java,v $
//
// Project:   	Tango Device Server
//
// Description:	java source code for the SnapArchiver class .
//              This class is a singleton class and implements everything
//              which exists only once for all the  SnapArchiver object
//              It inherits from the DeviceClass class.
//
// $Author: pierrejoseph $
//
// $Revision: 1.10 $
//
// $Log: SnapArchiverClass.java,v $
// Revision 1.10  2007/05/11 13:58:53  pierrejoseph
// Attribute addition : release version
//
// Revision 1.9  2007/04/04 13:45:29  ounsy
// new LaunchSnapShot command management
//
// Revision 1.8.2.1  2007/03/14 15:47:32  ounsy
// new LaunchSnapShot implementation
//
// Revision 1.8  2006/04/12 15:46:40  ounsy
// corrected the missing attributes problem
//
// Revision 1.7  2006/03/27 13:57:34  ounsy
// organized imports
//
// Revision 1.6  2005/11/29 17:33:03  chinkumo
// no message
//
// Revision 1.5.2.2  2005/11/29 16:16:50  chinkumo
// Code reformated (pogo compatible)
//
// Revision 1.5.2.1  2005/11/15 13:46:17  chinkumo
// ...
//
// Revision 1.5  2005/08/19 14:03:47  chinkumo
// no message
//
// Revision 1.4  2005/06/15 14:02:53  chinkumo
// The device was regenerated in Tango V5.
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-======================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

package SnapArchiver;

import java.util.ResourceBundle;
import java.util.Vector;

import fr.esrf.Tango.AttrWriteType;
import fr.esrf.Tango.DevFailed;
import fr.esrf.Tango.DispLevel;
import fr.esrf.TangoApi.DbDatum;
import fr.esrf.TangoDs.Attr;
import fr.esrf.TangoDs.Command;
import fr.esrf.TangoDs.DeviceClass;
import fr.esrf.TangoDs.DeviceImpl;
import fr.esrf.TangoDs.TangoConst;
import fr.esrf.TangoDs.Util;

public class SnapArchiverClass extends DeviceClass implements TangoConst
{
	/**
	 * SnapArchiverClass class instance (it is a singleton).
	 */
	private static SnapArchiverClass _instance = null;

	/**
	 * Class properties array.
	 */
	private DbDatum[] cl_prop = null;

	//--------- Start of properties data members ----------

	/**
	 * Computer identifier on wich is settled the database HDB. The identifier can be the computer name or its IP address. <br> <b>Default value : </b> localhost.
	 */
	String dbHost;
	/**
	 * Database name.<br> <b>Default value : </b> hdb
	 */
	String dbName;
	/**
	 * Database schema name.<br> <b>Default value : </b> snap
	 */
	String dbSchema;

//--------- End of properties data members ----------


//===================================================================			
//
// method : 		instance()
// 
// description : 	static method to retrieve the SnapArchiverClass object 
//					once it has been initialised
//
//===================================================================
	public static SnapArchiverClass instance()
	{
		if ( _instance == null )
		{
			System.err.println("SnapArchiverClass is not initialised !!!");
			System.err.println("Exiting");
			System.exit(-1);
		}
		return _instance;
	}

//===================================================================			
//
// method : 		Init()
// 
// description : 	static method to create/retrieve the SnapArchiverClass
//					object. This method is the only one which enables a 
//					user to create the object
//
// in :			- class_name : The class name
//
//===================================================================
	public static SnapArchiverClass init(String class_name) throws DevFailed
	{
		if ( _instance == null )
		{
			_instance = new SnapArchiverClass(class_name);
		}
		return _instance;
	}
	
//===================================================================			
//
// method : 		SnapArchiverClass()
// 
// description : 	constructor for the SnapArchiverClass class
//
// argument : in : 	- name : The class name
//
//===================================================================
	protected SnapArchiverClass(String name) throws DevFailed
	{
		super(name);

		Util.out2.println("Entering SnapArchiverClass constructor");
		write_class_property();
		get_class_property();

		Util.out2.println("Leaving SnapArchiverClass constructor");
	}
//	=============================================================================
//
//		Method:	attribute_factory(Vector att_list)
//
//	=============================================================================
public void attribute_factory(Vector att_list) throws DevFailed
{
   //  Attribute : version
   Attr version = new Attr("version" , Tango_DEV_STRING , AttrWriteType.READ);
   att_list.addElement(version);
}
		
//===================================================================			
//
// method : 		command_factory()
// 
// description : 	Create the command object(s) and store them in the
//					command list
//===================================================================
	public void command_factory()
	{
	    command_list.addElement(new LaunchSnapShotCmd("LaunchSnapShot" ,
		                                              Tango_DEV_SHORT , Tango_DEV_SHORT ,
		                                              "The snapshot associated context's identifier." ,
		                                              "" ,
		                                              DispLevel.OPERATOR));
		command_list.addElement(new CreateNewContextCmd("CreateNewContext" ,
		                                                Tango_DEVVAR_STRINGARRAY , Tango_DEV_VOID ,
		                                                "All the informations usefull to create a context ,Snapshot pattern)." ,
		                                                "" ,
		                                                DispLevel.OPERATOR));

		//	add polling if any
		for ( int i = 0 ; i < command_list.size() ; i++ )
		{
			Command cmd = ( Command ) command_list.elementAt(i);
		}
	}


//===================================================================			
//
// method : 		device_factory()
// 
// description : 	Create the device object(s) and store them in the 
//					device list
//
// argument : in : 	String[] devlist : The device name list
//
//===================================================================
	public void device_factory(String[] devlist) throws DevFailed
	{
		String device_version = ResourceBundle.getBundle("application").getString("project.version");
		
		for ( int i = 0 ; i < devlist.length ; i++ )
		{
			//Util.out4.println("Device name : " + devlist[ i ]);

			// Create device and add it into the device list
			//----------------------------------------------
			device_list.addElement(new SnapArchiver(this , devlist[ i ],device_version));

			// Export device to the outside world
			//----------------------------------------------
			if ( Util._UseDb == true )
				export_device(( ( DeviceImpl ) ( device_list.elementAt(i) ) ));
			else
				export_device(( ( DeviceImpl ) ( device_list.elementAt(i) ) ) , devlist[ i ]);
		}
	}
//===================================================================
	/**
	 * Get the class property for specified name.
	 *
	 * @param name The property name.
	 */
//===================================================================
	public DbDatum get_class_property(String name)
	{
		for ( int i = 0 ; i < cl_prop.length ; i++ )
			if ( cl_prop[ i ].name.equals(name) )
				return cl_prop[ i ];
		//	if not found, return  an empty DbDatum
		return new DbDatum(name);
	}

//===================================================================
	/**
	 * Read the class properties from database.
	 */
//===================================================================
	public void get_class_property() throws DevFailed
	{
		//	Initialize your default values here.
		//------------------------------------------


		//	Read class properties from database.(Automatic code generation)
		//-------------------------------------------------------------
		if ( Util._UseDb == false )
			return;
		String[] propnames = {
			"DbHost",
			"DbName",
			"DbSchema"
		};

		//	Call database and extract values
		//--------------------------------------------
		cl_prop = get_db_class().get_property(propnames);
		int i = -1;
		//	Extract DbHost value
		if ( cl_prop[ ++i ].is_empty() == false )
			dbHost = cl_prop[ i ].extractString();
		else
			cl_prop[ i ].insert(dbHost);

		//	Extract DbName value
		if ( cl_prop[ ++i ].is_empty() == false )
			dbName = cl_prop[ i ].extractString();
		else
			cl_prop[ i ].insert(dbName);

		//	Extract DbSchema value
		if ( cl_prop[ ++i ].is_empty() == false )
			dbSchema = cl_prop[ i ].extractString();
		else
			cl_prop[ i ].insert(dbSchema);

		//	End of Automatic code generation
		//-------------------------------------------------------------

	}

//===================================================================
	/**
	 * Set class description as property in database
	 */
//===================================================================
	private void write_class_property() throws DevFailed
	{
		//	First time, check if database used
		//--------------------------------------------
		if ( Util._UseDb == false )
			return;

		//	Prepeare DbDatum
		//--------------------------------------------
		DbDatum[] data = new DbDatum[ 2 ];
		data[ 0 ] = new DbDatum("ProjectTitle");
		data[ 0 ].insert("Tango Device Server");

		data[ 1 ] = new DbDatum("Description");
		data[ 1 ].insert("Device of Snapshoting system");

		//	Call database and and values
		//--------------------------------------------
		get_db_class().put_property(data);
	}

}
